### ISSUE TITLE
unison-fsmonitor

### ISSUE THREAD

**Issue by pkel** [croadfeldt/unison251-fedora#1]
Thanks for packaging the recent unison versions.

My main motivation to use 2.48/2.51 is that they come with the option to `-repeat watch`. This feature relies on
the executable `unison-fsmonitor` for monitoring changes to the filesystem. This binary seems to be missing in your package.

**Comment by BlauerHunger** [comment]
I'd like to have unison-fsmonitor available in the package (or as a separate package) as well. As a workaround I'm currently copying over the fsmonitor executable from the Arch Linux package.

**Comment by croadfeldt** [comment]
Added. Pushing updates to copr now.
