### ISSUE TITLE
Incompatibility between F32 and F33 builds

### ISSUE THREAD

**Issue by pkel** [croadfeldt/unison251-fedora#4]
Thanks for your packaging work.

```shell
$ # on Fedora 33
$ unison -version
unison version 2.51.3 (ocaml 4.11.0+dev2-2020-04-22)
$ # on Fedora 32
$ unison -version
unison version 2.51.3 (ocaml 4.10.0)
```

Syncing between F32 and F33 is not possible due to incompatibilities in the OCaml compiler. I get the following error message:
```
Fatal error: Server: Server: Fatal error during unmarshaling (input_value: unknown custom block identifier),
possibly because client and server have been compiled with different versions of the OCaml compiler.
```

I would appreciate if you fix the OCaml version across all builds. This would simplify the transition between Fedora versions. I usually avoid upgrading all machines at once.

Thanks for considering!

**Comment by croadfeldt** [comment]
Outdated issue.
